#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ButtonStyleMinusPrimaryMinusMMinusYellow

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle-Primary-M-Yellow.ButtonStyle-Primary-M-Yellow_C
// 0x0000 (0x0530 - 0x0530)
class UButtonStyleMinusPrimaryMinusMMinusYellow_C final : public UCommonButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ButtonStyle-Primary-M-Yellow_C">();
	}
	static class UButtonStyleMinusPrimaryMinusMMinusYellow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyleMinusPrimaryMinusMMinusYellow_C>();
	}
};
static_assert(alignof(UButtonStyleMinusPrimaryMinusMMinusYellow_C) == 0x000008, "Wrong alignment on UButtonStyleMinusPrimaryMinusMMinusYellow_C");
static_assert(sizeof(UButtonStyleMinusPrimaryMinusMMinusYellow_C) == 0x000530, "Wrong size on UButtonStyleMinusPrimaryMinusMMinusYellow_C");

}

