#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WorldLighting

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass WorldLighting.WorldLighting_C
// 0x0000 (0x03A0 - 0x03A0)
class AWorldLighting_C final : public AFortLevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WorldLighting_C">();
	}
	static class AWorldLighting_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWorldLighting_C>();
	}
};
static_assert(alignof(AWorldLighting_C) == 0x000008, "Wrong alignment on AWorldLighting_C");
static_assert(sizeof(AWorldLighting_C) == 0x0003A0, "Wrong size on AWorldLighting_C");

}

